language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install six numpy scipy tensorflow

script:
  - cd hyperengine/tests
  - python -m pytest curve_predictor_test.py data_set_test.py named_dict_test.py spec_test.py
